2.0-rc5

diff --git a/deltafi-cli/deltafi b/deltafi-cli/deltafi
--- a/deltafi-cli/deltafi
+++ b/deltafi-cli/deltafi
@@ -104,15 +104,36 @@ _command_check() {
 export DELTAFICLI_WORKDIR=$(cd $(dirname $(_readlink -f $0)) && pwd)
 export DELTAFI_DIR=$(dirname "$DELTAFICLI_WORKDIR")
 
+# shellcheck source=common
+. "$DELTAFICLI_WORKDIR/common"
+
+[ ! -f "$DELTAFICLI_WORKDIR/config" ] \
+  && echo "ERROR: No $DELTAFICLI_WORKDIR/config file found. " \
+  && echo "cp $DELTAFICLI_WORKDIR/config.template $DELTAFICLI_WORKDIR/config and adjust." \
+  && exit 1
+
+. "$DELTAFICLI_WORKDIR/config"
+
+if [ "$2" == "-v" ]; then
+  cli_log "ENV variables"
+  env | grep "DELTAFICLI_*"
+fi
+
+if [ -f "$DELTAFICLI_DISABLED_STATE_PATH" ]; then
+  if [[ "$1" != "reenable" && "$1" != "version" ]]; then
+    echo "The system is currently disabled, 'deltafi reenable' must be run prior to executing other commands"
+    exit
+  fi
+fi
 
 _command_check jq
 _command_check curl
 _command_check sed
-_command_check kubectl
 _command_check ruby
 
-# shellcheck source=common
-. "$DELTAFICLI_WORKDIR/common"
+if ! _is_standalone; then
+  _command_check kubectl
+fi
 
 cli_help() {
   cli_name=${0##*/}
@@ -187,25 +208,6 @@ Flags:
 "
   exit 1
 }
-
-[ ! -f "$DELTAFICLI_WORKDIR/config" ] \
-  && echo "ERROR: No $DELTAFICLI_WORKDIR/config file found. " \
-  && echo "cp $DELTAFICLI_WORKDIR/config.template $DELTAFICLI_WORKDIR/config and adjust." \
-  && exit 1
-
-. "$DELTAFICLI_WORKDIR/config"
-
-if [ "$2" == "-v" ]; then
-  cli_log "ENV variables"
-  env | grep "DELTAFICLI_*"
-fi
-
-if [ -f "$DELTAFICLI_DISABLED_STATE_PATH" ]; then
-  if [[ "$1" != "reenable" && "$1" != "version" ]]; then
-    echo "The system is currently disabled, 'deltafi reenable' must be run prior to executing other commands"
-    exit
-  fi
-fi
 
 case "$1" in
   clickhouse-cli)
